---
title: "MYCN NBL Subtyping"
output: 
  html_notebook:
    toc: TRUE
    toc_float: TRUE
date: 2022
---
# Set working directory
```{r}
setwd("~/OpenPedCan-analysis/analyses/molecular-subtyping-NBL")
```

# Load Libraries
```{r}
library(dplyr)
library(data.table)
```


# Load the data files 
```{r}
consensus_df<-as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/consensus_wgs_plus_cnvkit_wxs.tsv.gz"))
hist_df<- as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/histologies.tsv"))
cnv_cnvkit_df<-as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/cnv-cnvkit.seg.gz"))
cnv_controlfreec_df<-as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/cnv-controlfreec.tsv.gz"))
gene_expression_df<-as.data.frame(readRDS("/home/rstudio/OpenPedCan-analysis/data/gene-expression-rsem-tpm-collapsed.rds"))
```



# Part 1
### For each NBL sample, gather MYCN amplification status 
```{r}
#Step 1: Filter the neuroblastoma, ganglioneuroblastoma, and ganglioneuroma samples from hist file first

hist_filtered_df <- hist_df %>% filter(cancer_group=="Neuroblastoma"|
                                       cancer_group=="Ganglioneuroblastoma"|
                                        cancer_group=="Ganglioneuroma")

# Step 2: Filter the MCYN records from consensus_wgs_plus_cnvkit_wxs.tsv.gz
consensus_filtered_df <- consensus_df %>% filter(gene_symbol=="MYCN")

# Step 3 Join the two data frames to get MYCN details with respect to the diagnosis. Joining with the intersection of the data frames.
MYCN_df <- inner_join(hist_filtered_df,consensus_filtered_df,by= c("Kids_First_Biospecimen_ID" = "biospecimen_id"))

```

```{r}
print(unique(MYCN_df$experimental_strategy)) # No RNA-Seq
```
```{r}
print(unique(MYCN_df$RNA_library)) # No RNA-Seq
```
# Part 2
### Create alterations/output table for matched DNA/RNA biospecimens. Match ID can be adapted from the independent-samples module

```{r}
MYCN_df <- MYCN_df %>% mutate(match_id = paste(Kids_First_Participant_ID, sample_id, sep = "_"))
```





