---
title: "QC EFO MONDO Map file"
output: html_notebook
---

## Load libraries

```{r load_libraries}
suppressPackageStartupMessages({
  library(tidyverse)
})
```

## Read efo-mondo-map.tsv and histologies file

```{r read the two files}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
integrte_dir <- file.path(root_dir, 
                          "analyses", 
                          "molecular-subtyping-integrate",
                          "results")
results_dir <- file.path(root_dir,
                         "analyses",
                         "efo-mondo-mapping",
                         "results")

histology_df <- readr::read_tsv(file.path(integrte_dir, "histologies.tsv"), guess_max=100000)
efo_mondo_map <- readr::read_tsv(file.path(results_dir, "efo-mondo-map.tsv"))

```

## Check to make sure all cancer groups in histologies are in efo mondo map file

```{r}
cancer_group_summary <- histology_df %>% 
  dplyr::filter(!is.na(cancer_group)) %>% 
  dplyr::group_by(cancer_group) %>% 
  dplyr::mutate(n=n()) %>% 
  dplyr::select(cancer_group, n) %>%
  unique()

cancer_group_effective <- cancer_group_summary %>% 
  dplyr::filter(n>=3) %>% 
  pull(cancer_group)

all(cancer_group_effective %in% efo_mondo_map$cancer_group)
cancer_group_effective[!cancer_group_effective %in% efo_mondo_map$cancer_group] 

```

