#!/bin/bash
# Sangeeta Shukla

# Purpose: Automate search for EFO, MONDO, NCIT codes for cancer_group found in current release version of histologies.txt
# Note: Relevant cancer_group list extracted from efo-mondo-map-prefill.tsv
# efo-mondo-map-prefill.tsv file is generated by molecular-subtype-integrate module in OpenPenCan repo

# Followed by automated search for OLS codes for cancer_group, run a qc to ensure all cancer_group found in histologies.tsv (with samples >3)
# are mapped to their corresponding EFO, MONDO, and NCIT codes, post manual curation of the codes retrieved by automated search results



set -e
set -o pipefail

# This script should always run as if it were being called from
# the directory it lives in.
# copied from the run_in_ci.sh file at
# <https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/scripts/>
script_directory="$(perl -e 'use File::Basename;
 use Cwd "abs_path";
 print dirname(abs_path(@ARGV[0]));' -- "$0")"
cd "$script_directory" || exit


# Section 1: Run automated search to retrieve OLS codes

# Set up paths to data files to be consumed for analysis
source_dir="results"

# Set up paths to to write result files 
results_dir="results"

# Input data file path 
input_prefill_file="${source_dir}/efo-mondo-map-prefill.tsv"

ols_onto_type=("EFO" "MONDO" "NCIT")

ols_efo="EFO"
ols_mondo="MONDO"
ols_ncit="NCIT"


# Result file name
result_parsed_prefix="map-prefill"
result_parsed_suffix="codes.tsv"
merged_results="efo-mondo-map-prefill-auto.tsv"

# File name arguments
efo_auto_prefill="${result_parsed_prefix}-${ols_efo}-${result_parsed_suffix}"
mondo_auto_prefill="${result_parsed_prefix}-${ols_mondo}-${result_parsed_suffix}"
ncit_auto_prefill="${result_parsed_prefix}-${ols_ncit}-${result_parsed_suffix}"




for onto_type in "${ols_onto_type[@]}"
do
python3 00-search-ols-ontology-terms.py \
$input_prefill_file \
$onto_type \
"${result_parsed_prefix}-$onto_type-${result_parsed_suffix}"
done


# Merge prefill and auto search results in a single file
Rscript --vanilla 01-merge-auto-search-ols-terms.R \
--map_prefill "$input_prefill_file" \
--efo_auto_prefill "$efo_auto_prefill" \
--mondo_auto_prefill "$mondo_auto_prefill" \
--ncit_auto_prefill "$ncit_auto_prefill" \
--out_dir "$results_dir" \
--out_file "$merged_results"


# Remove intermediate data files        
for onto_type in "${ols_onto_type[@]}"
do
rm "${results_dir}/${result_parsed_prefix}-$onto_type-${result_parsed_suffix}"
done






# Section 2: Run QC for the efo-mondo-map.tsv file
Rscript -e "rmarkdown::render('02-qc_efo_mondo_map.Rmd', clean = TRUE)"
