---
title: "PedCBio Sample Name Column Addition"
author: Run Jin
output: html_notebook
---

```{r load library}
library(tidyverse)
library(readr)
```

### Define directories
```{r define directories}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "pedcbio-sample-name")
input_dir <- file.path(analysis_dir, "input")

results_dir <- file.path(analysis_dir, "results")
if(!dir.exists(results_dir)){
  dir.create(results_dir)
}
```

### Read in files
```{r read in files}
# histology file 
histology_df <- readr::read_tsv(file.path(data_dir, "histologies.tsv"), guess_max = 100000)

# read in all the pedcbio files
cbio_names_list <- list.files(input_dir)

files_list <- lapply(cbio_names_list, function(x){
  x <- readr::read_csv(file.path(input_dir, x))
})
```

### Update the ID for those samples if available 
```{r}
formatted_specimens_list <- lapply(files_list, function(x){

  # format them and select relevant columns
  formatted <- x %>% 
    dplyr::mutate(specimen_id = gsub("\\{", "", specimen_id)) %>% 
    dplyr::mutate(specimen_id = gsub("\\}", "", specimen_id)) %>% 
    dplyr::mutate(Kids_First_Biospecimen_ID = strsplit(specimen_id, ",")) %>% 
    unnest(Kids_First_Biospecimen_ID) %>%
    dplyr::select(Kids_First_Biospecimen_ID, formatted_sample_id)
  
  # add those to histology file
  histology_formatted_added <- histology_df %>%
    dplyr::filter(Kids_First_Biospecimen_ID %in% formatted$Kids_First_Biospecimen_ID) %>%
    left_join(formatted)

  return(histology_formatted_added)
})

# get the combined data
combined_histology_formatted_added <- do.call("rbind", formatted_specimens_list)
```

### Add IDs to those without sample id already
```{r}
# find the samples that do not have an ID yet 
histology_df_no_format_id <- histology_df %>%
  dplyr::filter(!Kids_First_Biospecimen_ID %in% combined_histology_formatted_added$Kids_First_Biospecimen_ID) 

# see which sample IDs need tie breaker
sample_ids <- histology_df_no_format_id %>% 
  pull(sample_id) %>% 
  unique()

# find the samples that need additional `tie-breaker`
samples_id_need_tiebreak <- c()
for (i in 1:length(sample_ids)){
  # deal with one sample at a time
  sample_id_of_interest <- sample_ids[i]
  
  # find the number of compositions
  n_comp <- histology_df_no_format_id %>% 
    dplyr::filter(sample_id == sample_id_of_interest) %>% 
    pull(composition) %>% 
    unique() %>% length()
  
  # store the samples with multiple compositions
  if(n_comp >1){
    samples_id_need_tiebreak <- c(samples_id_need_tiebreak, sample_id_of_interest)
  }
}

# see the samples that need tiebreak
check <- histology_df_no_format_id %>% 
  dplyr::filter(sample_id %in% samples_id_need_tiebreak)

```

